---
title: "V4_Creation of charts"
author: "Richard Alessi"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(ggplot2)
library(tibble)
library(xtable)
library(cowplot)
library(tidyverse)
library(data.table)
```



## Read in values
```{r}
setwd("C:/Users/richa/Desktop/Thesis/Results")
scenarioNumber = "2"
files_T2 = list.files(pattern = paste("Scenario", scenarioNumber,".*T2.*csv", sep = ""))
files_T2_RPTW = files_T2[grepl("RPTW", files_T2, fixed = TRUE)]
files_T2 = files_T2[!grepl("RPTW", files_T2, fixed = TRUE)]
```

```{r}
setwd("C:/Users/richa/Desktop/Thesis/Results")
start_time =  Sys.time()
df_T2 = do.call(rbind, lapply(files_T2, fread))
end_time =  Sys.time()
print(end_time - start_time)

df2_T2 = df_T2[df_T2$Model != "RA_ML Model_PlayTheWinnerRandomised", ]

df_RPTW = do.call(rbind, lapply(files_T2_RPTW, fread))
df2_T2 = rbind(df2_T2, df_RPTW)
```

```{r}
df2_T2$Perc_A = df2_T2$Allocation_TreatmentA/df2_T2$Sample_size 
df2_T2$AvgSuccess = df2_T2$Successes_total/df2_T2$Sample_size
df2_T2$Power = 1*(df2_T2$ChiSq_pvalue<=0.05)
```

```{r}
# Models
NeymanModels = c("RA_Known_Neyman", "CARA_Known_Neyman", "RA_Estimated_Neyman", "CARA_Estimated_Neyman", "RA_DBCD_Neyman", "CARA_DBCD_Neyman")
RSIHRModels = c("RA_Known_RSIHR", "CARA_Known_RSIHR", "RA_Estimated_RSIHR", "CARA_Estimated_RSIHR", "RA_DBCD_RSIHR", "CARA_DBCD_RSIHR")
RosenbergerModels = c("RA_Known_Rosenberger", "CARA_Known_Rosenberger", "RA_Estimated_Rosenberger", "CARA_Estimated_Rosenberger", "RA_DBCD_Rosenberger", "CARA_DBCD_Rosenberger")
OAModels = c("RA_Known_OptimallyAdjusted", "CARA_Known_OptimallyAdjusted", "RA_Estimated_OptimallyAdjusted", "CARA_Estimated_OptimallyAdjusted", "RA_DBCD_OptimallyAdjusted", "CARA_DBCD_OptimallyAdjusted")
GittinsModels = c("RA_Gittins_FALSE","RA_Gittins_TRUE")
MLModels = c("RA_ML Model_Random", "RA_ML Model_PlayTheWinner", "RA_ML Model_PlayTheWinnerRandomised", "RA_ML Model_EpsilonGreedy", "RA_ML Model_SoftMax")

PresoModels = c( "RA_ML Model_Random","RA_Estimated_RSIHR", "RA_Gittins_FALSE", "RA_ML Model_EpsilonGreedy")

TargetComparisonModels= c("RA_ML Model_Random", "RA_Estimated_Neyman", "RA_Estimated_RSIHR", "RA_Estimated_Rosenberger", "RA_Estimated_OptimallyAdjusted")

ImplementationModels=c("RA_Known_RSIHR","RA_Estimated_RSIHR","RA_DBCD_RSIHR")

RA_CARA_Models = c("RA_Estimated_RSIHR","RA_DBCD_RSIHR", "CARA_Estimated_RSIHR","CARA_DBCD_RSIHR")



```




# Table 1 - Tables of key values
```{r}
n_s = unique(df2_T2$Sample_Size)
models = unique(df2_T2$Model)

df_summary_T2 <- df2_T2 %>% group_by(Model, Sample_size) %>% summarise(averageSuccessProportion = mean(Successes_total/Sample_size), varSuccessProportion = var(Successes_total/Sample_size), averageAllocatedA = mean(Perc_A), VarAllocatedA = var(Perc_A), averagePower = mean(Power), varPower = var(Power), Z0_avg_all_A = mean(Z0_Allocation_TreatmentA/Sample_size), Z0_avg_successes_A = mean(Z0_Successes_TreatmentA/Sample_size), Z0_avg_successes_B = mean(Z0_Successes_TreatmentB/Sample_size), ChiSq_005 = mean(ifelse(is.na(ChiSq_pvalue),1,ChiSq_pvalue) <= 0.05), ChiSq_001 = mean(ifelse(is.na(ChiSq_pvalue),1,ChiSq_pvalue) <= 0.01), LR_test_005 = mean(ifelse(is.na(LR_test_pvalue),1,LR_test_pvalue) <= 0.05), LR_test_001 = mean(ifelse(is.na(LR_test_pvalue),1,LR_test_pvalue) <= 0.01), observations = n())

```





# Chart 3 - Average success proportion with sample size - T = 2
```{r}
labelMin = floor(min(df_summary_T2$averageAllocatedA)*20)/20
labelMax = ceiling(max(df_summary_T2$averageAllocatedA)*20)/20

labelMin2 = floor(min(df_summary_T2$averageSuccessProportion)*20)/20
labelMax2 = ceiling(max(df_summary_T2$averageSuccessProportion)*20)/20
```


```{r}
df_summary_T2$label <- NA
df_summary_T2$label[which(df_summary_T2$Sample_size == max(df_summary_T2$Sample_size))] <- df_summary_T2$Model[which(df_summary_T2$Sample_size == max(df_summary_T2$Sample_size))]

df_summary_T2 %>%
    mutate(LongName = recode(label, 
               `RA_ML Model_Random` = "Random",
                RA_Known_RSIHR = "RSIHR_Known", 
                RA_Estimated_RSIHR = "RSIHR_Estimated",
                RA_DBCD_RSIHR = "RSIHR_DABCD",
                CARA_Estimated_RSIHR = "RSIHR_CARA_Estimated",
                CARA_DBCD_RSIHR = "RSIHR_CARA_DABCD",
                RA_Gittins_FALSE = "Gittins",
               `RA_ML Model_EpsilonGreedy` = "Epsilon greedy"
                             )
           ) ->    df_summary_T2

df_summary_T2 %>%
    mutate(LongName_Model = recode(label, 
               `RA_ML Model_Random` = "Random",
                RA_Estimated_Neyman = "Neyman", 
                RA_Estimated_RSIHR = "RSIHR",
                RA_Estimated_Rosenberger = "Rosenberger",
                RA_Estimated_OptimallyAdjusted = "Optimally Adjusted",
                CARA_Estimated_RSIHR = "RSIHR_CARA_Estimated",
                CARA_DBCD_RSIHR = "RSIHR_CARA_DABCD",
                RA_Gittins_FALSE = "Gittins",
               `RA_ML Model_EpsilonGreedy` = "Epsilon greedy"
                             )
           ) ->    df_summary_T2


df_summary_T2 %>%
    mutate(LongName_Implement = recode(label, 
               `RA_ML Model_Random` = "Random",
                RA_Known_RSIHR = "Known", 
                RA_Estimated_RSIHR = "Estimated",
                RA_DBCD_RSIHR = "DABCD",)
           ) ->    df_summary_T2

df_summary_T2 %>%
    mutate(LongName_RA_CARA = recode(label, 
               `RA_ML Model_Random` = "Random",
                RA_Estimated_RSIHR = "RSIHR_Estimated",
                RA_DBCD_RSIHR = "RSIHR_DABCD",
                CARA_Estimated_RSIHR = "RSIHR_CARA_Estimated",
                CARA_DBCD_RSIHR = "RSIHR_CARA_DABCD",
                             )
           ) ->    df_summary_T2

df_summary_T2 %>%
    mutate(LongName_all = recode(Model, 
               `RA_ML Model_Random` = "Random",
                RA_Known_RSIHR = "RSIHR_Known", 
                RA_Estimated_RSIHR = "RSIHR_Estimated",
                RA_DBCD_RSIHR = "RSIHR_DABCD",
                CARA_Estimated_RSIHR = "RSIHR_CARA_Estimated",
                CARA_DBCD_RSIHR = "RSIHR_CARA_DABCD",
                RA_Gittins_FALSE = "Gittins",
               `RA_ML Model_EpsilonGreedy` = "Epsilon greedy"
                             )
           ) ->    df_summary_T2

```

```{r}

p1 = ggplot(data = df_summary_T2[df_summary_T2$Model %in% PresoModels,], aes(Sample_size, averageAllocatedA, color = Model), width = 100, height = 100) +geom_line()+xlab("Sample size")+geom_label_repel(aes(label = LongName),nudge_x = 0,na.rm = TRUE) + ylab("Average Treatment A Allocation")+ scale_y_continuous(labels = scales::percent, limits = c(0.4, 1))+scale_x_continuous(trans='log10') +
  theme(legend.position = "none")

p2 = ggplot(data = df_summary_T2[df_summary_T2$Model %in% PresoModels,], aes(Sample_size, averageSuccessProportion, color = Model), width = 200, height = 200) +geom_line()+geom_label_repel(aes(label = LongName),nudge_x = 0,na.rm = TRUE)+xlab("Sample size") + ylab("Total success proprtion average")+ scale_y_continuous(labels = scales::percent, limits = c(labelMin2, labelMax2))+scale_x_continuous(trans='log10')+
  theme(legend.position = "none")
  
plot_grid(p1, p2, ncol = 1, align = 'hv')

ggsave(paste("C:/Users/richa/Desktop/Thesis/Images/Presentation/Preso_models_1",scenarioNumber,".pdf", sep = ""), device = "pdf",  width = 30, height = 15, units = "cm")
```

```{r}
p1 = ggplot(data = df_summary_T2[df_summary_T2$Model %in% TargetComparisonModels,], aes(Sample_size, averageAllocatedA, color = Model), width = 100, height = 100) +geom_line()+xlab("Sample size")+geom_label_repel(aes(label = LongName_Model),nudge_x = 0,na.rm = TRUE) + ylab("Average Treatment A Allocation")+ scale_y_continuous(labels = scales::percent, limits = c(labelMin, labelMax))+scale_x_continuous(trans='log10') +
  theme(legend.position = "none")

p2 = ggplot(data = df_summary_T2[df_summary_T2$Model %in% TargetComparisonModels,], aes(Sample_size, averageSuccessProportion, color = Model), width = 200, height = 200) +geom_line()+geom_label_repel(aes(label = LongName_Model),nudge_x = 0,na.rm = TRUE)+xlab("Sample size") + ylab("Total success proprtion average")+ scale_y_continuous(labels = scales::percent, limits = c(labelMin2, labelMax2))+scale_x_continuous(trans='log10')+
  theme(legend.position = "none")
  
plot_grid(p1, p2, ncol = 1, align = 'hv')

ggsave(paste("C:/Users/richa/Desktop/Thesis/Images/Presentation/Preso_TargetComparisonModels_1_Sc",scenarioNumber,".pdf", sep = ""), device = "pdf",  width = 30, height = 15, units = "cm")
```


```{r}
p1 = ggplot(data = df_summary_T2[df_summary_T2$Model %in% ImplementationModels,], aes(Sample_size, averageAllocatedA, color = Model), width = 100, height = 100) +geom_line()+xlab("Sample size")+geom_label_repel(aes(label = LongName_Implement),nudge_x =0,na.rm = TRUE) + ylab("Average Treatment A Allocation")+ scale_y_continuous(labels = scales::percent, limits = c(0.5, 0.6))+scale_x_continuous(trans='log10') +
  theme(legend.position = "none")

p2 = ggplot(data = df_summary_T2[df_summary_T2$Model %in% ImplementationModels,], aes(Sample_size, averageSuccessProportion, color = Model), width = 200, height = 200) +geom_line()+geom_label_repel(aes(label = LongName_Implement),nudge_x = 0,na.rm = TRUE)+xlab("Sample size") + ylab("Total success proprtion average")+ scale_y_continuous(labels = scales::percent, limits = c(0.4, 0.43))+scale_x_continuous(trans='log10')+
  theme(legend.position = "none")
  
plot_grid(p1, p2, ncol = 1, align = 'hv')

ggsave(paste("C:/Users/richa/Desktop/Thesis/Images/Presentation/Preso_ImplementationModels_1_Sc",scenarioNumber,".pdf", sep = ""), device = "pdf",  width = 30, height = 15, units = "cm")
```

```{r}
p1 = ggplot(data = df_summary_T2[df_summary_T2$Model %in% RA_CARA_Models,], aes(Sample_size, averageAllocatedA, color = Model), width = 100, height = 100) +geom_line()+xlab("Sample size")+geom_label_repel(aes(label = LongName_RA_CARA),nudge_x = 0,na.rm = TRUE) + ylab("Average Treatment A Allocation")+ scale_y_continuous(labels = scales::percent, limits = c(0.48, 0.58))+scale_x_continuous(trans='log10') +
  theme(legend.position = "none")

p2 = ggplot(data = df_summary_T2[df_summary_T2$Model %in% RA_CARA_Models,], aes(Sample_size, averageSuccessProportion, color = Model), width = 200, height = 200) +geom_line()+geom_label_repel(aes(label = LongName_RA_CARA),nudge_x = 0,na.rm = TRUE)+xlab("Sample size") + ylab("Total success proprtion average")+ scale_y_continuous(labels = scales::percent, limits = c(0.4, 0.43))+scale_x_continuous(trans='log10')+
  theme(legend.position = "none")
  
plot_grid(p1, p2, ncol = 1, align = 'hv')

ggsave(paste("C:/Users/richa/Desktop/Thesis/Images/Presentation/Preso_RA_CARA_Models_1_Sc",scenarioNumber,".pdf", sep = ""), device = "pdf",  width = 30, height = 15, units = "cm")
```







# Chart 5 Chi Sq power with sample size
## 1. Alpha = 0.05 
```{r}
labelMin = floor(min(df_summary_T2$ChiSq_005)*20)/20
labelMax = ceiling(max(df_summary_T2$ChiSq_005)*20)/20

ylabel = "Power of Chi-Squared test (5% LoS)"
```

```{r}
ggplot(data = df_summary_T2[df_summary_T2$Model %in% PresoModels,], aes(Sample_size, ChiSq_005, color = Model), width = 200, height = 200) +geom_line()+geom_label_repel(aes(label = LongName),nudge_x = 0,na.rm = TRUE)+xlab("Sample size") + 
  ylab(ylabel)+ scale_y_continuous(labels = scales::percent, limits = c(labelMin, labelMax))+scale_x_continuous(trans='log10')+
  theme(legend.position = "none")

ggsave(paste("C:/Users/richa/Desktop/Thesis/Images/Presentation/Preso_Power_Models_1_Sc",scenarioNumber,".pdf", sep = ""), device = "pdf",  width = 20, height = 15, units = "cm")
```

  
```{r}
ggplot(data = df_summary_T2[df_summary_T2$Model %in% TargetComparisonModels,], aes(Sample_size, ChiSq_005, color = Model), width = 200, height = 200) +geom_line()+geom_label_repel(aes(label = LongName_Model),nudge_x = 0,na.rm = TRUE)+xlab("Sample size") + 
  ylab("Power of Chi-Squared test (5% LoS)")+ scale_y_continuous(labels = scales::percent, limits = c(labelMin, labelMax)) + scale_x_continuous(trans='log10')+
  theme(legend.position = "none")

ggsave(paste("C:/Users/richa/Desktop/Thesis/Images/Presentation/Preso_Power_TargetAllocations_1_Sc",scenarioNumber,".pdf", sep = ""), device = "pdf",  width = 20, height = 15, units = "cm")

```   


```{r}
ggplot(data = df_summary_T2[df_summary_T2$Model %in% ImplementationModels,], aes(Sample_size, ChiSq_005, color = Model), width = 200, height = 200) +geom_line()+geom_label_repel(aes(label = LongName_Implement),nudge_x = 0,na.rm = TRUE)+xlab("Sample size") + 
  ylab("Power of Chi-Squared test (5% LoS)")+ scale_y_continuous(labels = scales::percent, limits = c(labelMin, labelMax)) +scale_x_continuous(trans='log10')+
  theme(legend.position = "none")

ggsave(paste("C:/Users/richa/Desktop/Thesis/Images/Presentation/Preso_Power_ImplementationModels_1_Sc",scenarioNumber,".pdf", sep = ""), device = "pdf",  width = 20, height = 15, units = "cm")

```   


```{r}
ggplot(data = df_summary_T2[df_summary_T2$Model %in% RA_CARA_Models,], aes(Sample_size, ChiSq_005, color = Model), width = 200, height = 200) +geom_line()+geom_label_repel(aes(label = LongName_RA_CARA),nudge_x = 0,na.rm = TRUE)+xlab("Sample size") + 
  ylab("Power of Chi-Squared test (5% LoS)")+ scale_y_continuous(labels = scales::percent, limits = c(labelMin, labelMax)) +scale_x_continuous(trans='log10')+
  theme(legend.position = "none")

ggsave(paste("C:/Users/richa/Desktop/Thesis/Images/Presentation/Preso_Power_RA_CARA_Models_1_Sc",scenarioNumber,".pdf", sep = ""), device = "pdf",  width = 20, height = 15, units = "cm")

```   






# Chart 7 Scatter of power and average success
## n = 50
```{r}
ggplot(data = df_summary_T2[df_summary_T2$Sample_size == 50,], aes(x = averageSuccessProportion , y = ChiSq_005, color = Model), width = 200) + geom_point() +xlab("Average total successes") + ylab("Power of Chi-Squared test (5% LoS)")+ scale_y_continuous(labels = scales::percent) + scale_x_continuous(labels = scales::percent) 
ggsave(paste("C:/Users/richa/Desktop/Thesis/Images/Presentation/Preso_Scatter_n50_2_with_legend_Scenario_",scenarioNumber,".pdf", sep = ""), device = "pdf", width = 70, units = "cm")
```






