---
title: "V4_AllCombined"
author: "Richard Alessi"
date: "`r Sys.Date()`"
output: pdf_document
---
```{r}
library(stringr)
library(foreach)
library(parallel)
library(iterators)
library(doParallel)

library(lmtest)
library(zoo)
```


```{r}
# Results measures
source("./ResultMeasures/successCount.R")
source("./ResultMeasures/successTreatmentCount.R")

# Helper files
source("./Helpers/Initialise_RR.R")
source("./Helpers/InitialiseWCovariates_RR.R")
source("./Helpers/ChiSq_calc.R")
source("./Helpers/LR_test_calc.R")
source("./Helpers/DBCD_G_Multi_Function.R")
```

# Allocation methods we will use
```{r}
source("./NewModels/1_ResponseAdaptive.r")
source("./NewModels/2_CARA.r")
source("./NewModels/3_MLMethods.R")
source("./Models/RA/11_GittinsIndex.R")
GI = readRDS("C:/Users/richa/Desktop/Thesis/Code/thesis/Helpers/GittinsMatrix.rds")
```

# Set up simulation parameters
```{r}
runs = 1
n_max = 100
n_min = 10
n_step = 10
n0 = 3

SuccessProbs_known = c(0.4, 0.4)

SuccessProbs = matrix(data = c(0.4, 0.4, 0.4, 0.4), nrow = 2, ncol = 2)

params = data.frame(c_gamma = 3,temp = 5,eps = 0.1)

Model_allocations = c("Neyman", "RSIHR", "Rosenberger", "OptimallyAdjusted")
Model_estimations = c("Known", "Estimated", "DBCD")

ML_Allocations = c("Random", "PlayTheWinner", "PlayTheWinnerRandomised", "EpsilonGreedy", "SoftMax")

```

```{r}
RunModel_RA <- function(AllocationMethod, EstimationMethod, n_max, n_min, n_step, n0, Z, Results, k, p_known, params){
  c_gamma = params$c_gamma
  SuccessProbs_known = colMeans(p_known)
  Allocation = ResponseAdaptive(n_max, n0, Results, AllocationMethod = AllocationMethod, EstimationMethod = EstimationMethod, p_known =  SuccessProbs_known, gam = c_gamma)

df_combined = data.frame()
n_s = n_step*((n_min/n_step):(n_max/n_step))
  
for(j in n_s){
  TotalSuccesses = successCount(Allocation[1:j], Results[1:j,])
  TotalTreatmentSuccesses = successTreatmentCount(Allocation[1:j], Results[1:j,])
  
  Z0_TotalSuccesses = successCount(Allocation[1:j][Z[1:j]==0], Results[1:j,][Z[1:j]==0,])
  Z0_TotalTreatmentSuccesses = successTreatmentCount(Allocation[1:j][Z[1:j]==0], Results[1:j,][Z[1:j]==0,])
  
  
  df_update = c(paste("RA", EstimationMethod, AllocationMethod, sep = "_"),
                k, j, 
                TotalSuccesses,
                as.character(list(TotalTreatmentSuccesses)),
                as.character(list(table(Allocation[1:j]))), 
                Z0_TotalSuccesses,
                as.character(list(Z0_TotalTreatmentSuccesses)),
                as.character(list(table(Allocation[1:j][Z[1:j]==0]))),
                ChiSq_calc(Allocation[1:j], Results[1:j,]),
                LR_test_calc(Allocation[1:j], Results[1:j,], Z[1:j]),
                as.character(list(params)),
                as.character(list(c(p_known)))
  )
  df_combined = rbind(df_combined,data.frame(t(df_update)))
}
  return(df_combined)
}

RunModel_CARA <- function(AllocationMethod, EstimationMethod,  n_max, n_min, n_step, n0, Z, Results, k, p_known, params){
  c_gamma = params$c_gamma
  Allocation = CARA(Results, n0, Z, AllocationMethod = AllocationMethod, EstimationMethod = EstimationMethod, p_known =  p_known, gam = c_gamma)
  TotalSuccesses = successCount(Allocation, Results)
  TotalTreatmentSuccesses = successTreatmentCount(Allocation, Results)
  
df_combined = data.frame()
n_s = n_step*((n_min/n_step):(n_max/n_step))
  
for(j in n_s){
  TotalSuccesses = successCount(Allocation[1:j], Results[1:j,])
  TotalTreatmentSuccesses = successTreatmentCount(Allocation[1:j], Results[1:j,])
  
  Z0_TotalSuccesses = successCount(Allocation[1:j][Z[1:j]==0], Results[1:j,][Z[1:j]==0,])
  Z0_TotalTreatmentSuccesses = successTreatmentCount(Allocation[1:j][Z[1:j]==0], Results[1:j,][Z[1:j]==0,])
  
  
  df_update = c(paste("RA", EstimationMethod, AllocationMethod, sep = "_"),
                k, j, 
                TotalSuccesses,
                as.character(list(TotalTreatmentSuccesses)),
                as.character(list(table(Allocation[1:j]))), 
                Z0_TotalSuccesses,
                as.character(list(Z0_TotalTreatmentSuccesses)),
                as.character(list(table(Allocation[1:j][Z[1:j]==0]))),
                ChiSq_calc(Allocation[1:j], Results[1:j,]),
                LR_test_calc(Allocation[1:j], Results[1:j,], Z[1:j]),
                as.character(list(params)),
                as.character(list(c(p_known)))
  )
  df_combined = rbind(df_combined,data.frame(t(df_update)))
}
  return(df_combined)
}


RunModel_ML <- function(AllocationMethod,  n_max, n_min, n_step, n0, Z, Results, k, p_known, params){
  temp = params$temp
  eps = params$eps
  Allocation = ML_Methods(n0, Results, Method = AllocationMethod, eps, temp)
  

df_combined = data.frame()
n_s = n_step*((n_min/n_step):(n_max/n_step))
  
for(j in n_s){
  TotalSuccesses = successCount(Allocation[1:j], Results[1:j,])
  TotalTreatmentSuccesses = successTreatmentCount(Allocation[1:j], Results[1:j,])
  
  Z0_TotalSuccesses = successCount(Allocation[1:j][Z[1:j]==0], Results[1:j,][Z[1:j]==0,])
  Z0_TotalTreatmentSuccesses = successTreatmentCount(Allocation[1:j][Z[1:j]==0], Results[1:j,][Z[1:j]==0,])
  
  
  df_update = c(paste("RA", "ML Model", AllocationMethod, sep = "_"),
                k, j, 
                TotalSuccesses,
                as.character(list(TotalTreatmentSuccesses)),
                as.character(list(table(Allocation[1:j]))), 
                Z0_TotalSuccesses,
                as.character(list(Z0_TotalTreatmentSuccesses)),
                as.character(list(table(Allocation[1:j][Z[1:j]==0]))),
                ChiSq_calc(Allocation[1:j], Results[1:j,]),
                LR_test_calc(Allocation[1:j], Results[1:j,], Z[1:j]),
                as.character(list(params)),
                as.character(list(c(p_known)))
  )
  df_combined = rbind(df_combined,data.frame(t(df_update)))
}
  return(df_combined)
}

RunModel_Gittins <- function( n_max, n_min, n_step, n0, Z, Results, k, p_known, Random, GI){
  Allocation = GittinsIndex(n0, Results, GI, Random)

df_combined = data.frame()
n_s = n_step*((n_min/n_step):(n_max/n_step))
  
for(j in n_s){
  TotalSuccesses = successCount(Allocation[1:j], Results[1:j,])
  TotalTreatmentSuccesses = successTreatmentCount(Allocation[1:j], Results[1:j,])
  
  Z0_TotalSuccesses = successCount(Allocation[1:j][Z[1:j]==0], Results[1:j,][Z[1:j]==0,])
  Z0_TotalTreatmentSuccesses = successTreatmentCount(Allocation[1:j][Z[1:j]==0], Results[1:j,][Z[1:j]==0,])
  
  
  df_update = c(paste("RA", "Gittins", as.character(Random), sep = "_"),
                k, j, 
                TotalSuccesses,
                as.character(list(TotalTreatmentSuccesses)),
                as.character(list(table(Allocation[1:j]))), 
                Z0_TotalSuccesses,
                as.character(list(Z0_TotalTreatmentSuccesses)),
                as.character(list(table(Allocation[1:j][Z[1:j]==0]))),
                ChiSq_calc(Allocation[1:j], Results[1:j,]),
                LR_test_calc(Allocation[1:j], Results[1:j,], Z[1:j]),
                as.character(list(params)),
                as.character(list(c(p_known)))
  )
  df_combined = rbind(df_combined,data.frame(t(df_update)))
}
  return(df_combined)
}

```



```{r}

runSims = function(k,  n_max, n_min, n_step, n0, SuccessProbs, params, GI) {
  
  df = data.frame(
    Model = character(),
    Run = integer(),
    Sample_size = integer(),
    Successes_total = integer(),
    Success_by_treatment = character(),
    Allocation_by_treatment = character(),
    Z0_Successes_total = integer(),
    Z0_Success_by_treatment = character(),
    Z0_Allocation_by_treatment = character(),
    ChiSq_pvalue = double(),
    LR_test_pvalue = double(),
    Parameters = character(),
    Success_Probabilities = character()
  )
  
  c_names = colnames(df)

  # Results
  Tr = dim(SuccessProbs)[2]
  Results = matrix(0, nrow = n_max, ncol = Tr)
  Z = rbinom(n_max,1,0.5) # Simulate single binary covariate

  for (i in 1:Tr) {
    Results[ , i] = rbinom(n_max, 1, SuccessProbs[Z+1, i]) 
  }
  
  SuccessProbs_known = colMeans(SuccessProbs)


# Run models
  for (AM in Model_allocations) {
    for (EM in Model_estimations) {
      df = rbind(df, RunModel_RA(AllocationMethod = AM, EstimationMethod = EM,  n_max, n_min, n_step, n0, Z, Results, k, p_known = SuccessProbs, params), deparse.level = 2)
      df = rbind(df, RunModel_CARA(AllocationMethod = AM, EstimationMethod = EM,  n_max, n_min, n_step, n0, Z, Results, k, p_known = SuccessProbs, params), deparse.level = 1)
    }
    
  }
  
  
# Run remaining models
  for (M in ML_Allocations) {
     df= rbind(df, RunModel_ML(M,  n_max, n_min, n_step, n0, Z, Results, k, SuccessProbs_known, params), deparse.level = 1)
  }
  
# Run gittins
  df= rbind(df, RunModel_Gittins( n_max, n_min, n_step, n0, Z, Results, k, SuccessProbs, TRUE, GI), deparse.level = 1)
  df= rbind(df, RunModel_Gittins( n_max, n_min, n_step, n0, Z, Results, k, SuccessProbs, FALSE, GI), deparse.level = 1)
  
 colnames(df) = c_names
 return(df)
}


```


```{r}
numCores <- parallel::detectCores() # Requires library(parallel)
cl = makeCluster(numCores)
registerDoParallel(cl)
print(numCores)
```

```{r}
SuccessProbs_known = c(0.4, 0.4)

SuccessProbs = matrix(data = c(0.4, 0.4, 0.4, 0.4), nrow = 2, ncol = 2)
```



```{r}
start_time <- Sys.time()
resultsCombined = foreach(k = 1:runs, .combine = rbind) %dopar% {
  res = runSims(k,  n_max, n_min, n_step, n0, SuccessProbs, params, GI)
  return(res)
}

end_time <- Sys.time()

end_time - start_time
```



```{r}
write.csv(resultsCombined, file = paste("C:/Users/richa/Desktop/Thesis/V3_Results/Scenario_5_Full_T2_",format(Sys.time(), "%Y%m%d"),".csv", sep = ""))
```

```{r}
SuccessProbs_known = c(0.6, 0.2)

SuccessProbs = matrix(data = c(0.4, 0.8, 0.3, 0.1), nrow = 2, ncol = 2)
```



```{r}
start_time <- Sys.time()
resultsCombined = foreach(k = 1:runs, .combine = rbind) %dopar% {
  res = runSims(k,  n_max, n_min, n_step, n0, SuccessProbs, params, GI)
  return(res)
}

end_time <- Sys.time()

end_time - start_time
```



```{r}
write.csv(resultsCombined, file = paste("C:/Users/richa/Desktop/Thesis/V3_Results/Scenario_1_Full",format(Sys.time(), "%Y%m%d"),".csv", sep = ""))
```

```{r}
SuccessProbs_known = c(0.5, 0.3)

SuccessProbs = matrix(data = c(0.5, 0.5, 0.3, 0.3), nrow = 2, ncol = 2)
```



```{r}
start_time <- Sys.time()
resultsCombined = foreach(k = 1:runs, .combine = rbind) %dopar% {
  res = runSims(k,  n_max, n_min, n_step, n0, SuccessProbs, params, GI)
  return(res)
}

end_time <- Sys.time()

end_time - start_time
```



```{r}
write.csv(resultsCombined, file = paste("C:/Users/richa/Desktop/Thesis/V3_Results/Scenario_4_Full_T2_",format(Sys.time(), "%Y%m%d"),".csv", sep = ""))
```


```{r}
stopCluster(cl)
```


```{r}

SuccessProbs = matrix(data = c(0.04, 0.08, 0.03, 0.01), nrow = 2, ncol = 2)

res = runSims(1,  n_max, n_min, n_step, n0, SuccessProbs, params, GI)

```

